RNA_Codons = {
    # 'M' - START, '*' - STOP
    "A": ["GCU", "GCC", "GCA", "GCG"],
    "C": ["UGU", "UGC"],
    "D": ["GAU", "GAC"],
    "E": ["GAA", "GAG"],
    "F": ["UUU", "UUC"],
    "G": ["GGU", "GGC", "GGA", "GGG"],
    "H": ["CAU", "CAC"],
    "I": ["AUA", "AUU", "AUC"],
    "K": ["AAA", "AAG"],
    "L": ["UUA", "UUG", "CUU", "CUC", "CUA", "CUG"],
    "M": ["AUG"],
    "N": ["AAU", "AAC"],
    "P": ["CCU", "CCC", "CCA", "CCG"],
    "Q": ["CAA", "CAG"],
    "R": ["CGU", "CGC", "CGA", "CGG", "AGA", "AGG"],
    "S": ["UCU", "UCC", "UCA", "UCG", "AGU", "AGC"],
    "T": ["ACU", "ACC", "ACA", "ACG"],
    "V": ["GUU", "GUC", "GUA", "GUG"],
    "W": ["UGG"],
    "Y": ["UAU", "UAC"],
    "*": ["UAA", "UAG", "UGA"]
}

aminoacid_seq = "MLVNIADYMMEYVAVMSIPRAISAAKGTHKAKEPGYMFPVFWCVPIRHACAETGRSYTGGINLREFPHITPMTCFCNKAIRVHLFCAGEKEPEQDPVNLETHNIIKQYDRFMMNGGHTRHQASHPPCPLGIFTLIESLKLLVKPWASDHNDYLKKLPPSMFYWRCYQAFEPPWAWDACADRVTAGTSRIRIFARFPTCCDHTCYNHIGDMVFVMYKSNPDLSEVCRIHQEFSKTQHVIAWNESTPRNNDIGGTHHGIVICDVTCPVMECDCNVPYLVHQMPCLEHSFKHNKSHRYWAKPIFTGRMASWHFQMDKWKINHNMGNMHAAKELDIHNGGDYFIGFSKVLTWLTDMAVISDCFFENSPCRCYCGLPEGFQCQGPQMYHDIIKERDMARIYANHSGGNQPQLPEPRVIMRHTGYDDESPTCDKNKAGPFWTGTWRMARCGPYAVAKCFPQCGVYVMWSIGHAHPPDRWLSQEYTMWRHLPCVVWTLIDTFHSLCLCFSVGFQTNDNMPAARQRSYLWEPWYLVTRDSHQGMKVMDERWEETTVCSVENPNCWQEVYIMWGNPRICPRGPQTWHAPWWHCHWLDQEKAPVKMTGYNYPWDQMCKGDAPHNWTPAKWQLDFAWKADVRPHELEDSTIARTMRCFAEDAQYLMGKSHMSGPDPPWYNFMWQHACAYHHCQKQYPTCWTPPGIKIMDYHLCWEMGWGKIKMNMMCIMERDGSDILACIPSRPMANETPCLNLCARGEFDCMICQYLGTTCARKDWSEKLMGPPEPDFQENVEMHRVTAQTVGVRNWRPYQAMKVRLHLSPRRQASTIHHDTKCCRLMQHWADAKKIWNCYLISNFVNRDKPMCCCRPDNTMTYFENTPQRPNIQEGTGGQQNREFILFQGDYEVECNEKHVVRVQTWRAQQIYLCNVCPKSIMFWNQADGQFGVVHRMPFWMFFFSPITANMTGHTHKLQDQKQYLNKVLQFMEHCAWGNTDFWAITHRDNMWNAI"
codons_list = []
codons_num_list = []
i = 0

for aminoacid in aminoacid_seq:
    if aminoacid in RNA_Codons:
        codons_list.append(RNA_Codons[aminoacid])
        codons_num_list.append(len(codons_list[i]))
        i += 1 
print(codons_list)  
print(codons_num_list)

#millions = []
codons_num = 1
for i in range(0, len(codons_num_list)-1):
    codons_num *= codons_num_list[i]
    #millions = [codons_num//1000000000, codons_num%1000000000]
print(codons_num)